import {
  AlertTriangle,
  AlignRight,
  ArrowRight,
  AtSign,
  Book,
  Cat,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Coins,
  CreditCard,
  CreditCardIcon,
  Crown,
  DatabaseZap,
  File,
  FileText,
  Gift,
  Heart,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Lock,
  LucideIcon,
  MessageCircleIcon,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Percent,
  Pizza,
  Plus,
  SearchCheck,
  Settings,
  StickyNoteIcon,
  SunMedium,
  Trash,
  User,
  Wand,
  X,
} from 'lucide-react';

interface IconMap {
  [key: string]: LucideIcon;
}
export const Icons: IconMap = {
  logo: Cat,
  coins: Coins,
  crown: Crown,
  notebook: StickyNoteIcon,
  book: Book,
  percent: Percent,
  wand: Wand,
  menu: AlignRight,
  heart: Heart,
  card: CreditCardIcon,
  helpCircle: HelpCircle,
  atsign: AtSign,
  search: SearchCheck,
  database: DatabaseZap,
  more: MoreHorizontal,
  moveUp: ChevronUp,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  message: MessageCircleIcon,
  sun: SunMedium,
  moon: Moon,
  gift: Gift,
  lock: Lock,
  laptop: Laptop,

  check: Check,
};
